### PR TITLE
dockerize application

### LINKED ISSUE #73: Adapt CI/CD for Kotlin
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [ ] Story is reviewed and accepted by PO
- [x] Story is tested by DEV-Engineer
- [x] Documentation extended if required

---

**Business value**
As an engineer, I want to have working Github workflows, so that I'm sure new commited code is working and tested as expected.

**Description**
Adapt all Github workflows to the new Kotlin implementation of the backend.

**Open points**

**Preconditions**

**Acceptance criterias**

**Not in scope**

**Implementation details**

**Test case description**
Not needed

**Involved contacts**
PO: @tonymowers 
TE: @janfuhrer

### PR DESCRIPTION
**Pull request by janfuhrer**
closes #73

### CODE REVIEW

**Review by Andy-Bigler — APPROVED** [review]

**Comment by janfuhrer** [comment]
Building works, the backend container fails at the moment with following message:

```java
2022-10-23 13:11:48.965  WARN 7 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 42P01
2022-10-23 13:11:48.965 ERROR 7 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: relation "employee" does not exist
```

**Comment by janfuhrer** [comment]
solved with schema `public`

**Comment by Andy-Bigler** [comment]
Is this correct? Like that I get a folder data in the project root.
    volumes:
    - ./data:/var/lib/postgresql/data
    
Before it was like this:
    volumes:
    - pb_data:/pb_data
    
    volumes:
         pb_data: {}

**Comment by janfuhrer** [comment]
fix: use docker volumes with #82

**Pull request merged**
