### PR TITLE
feat: add group rest endpoint

### LINKED ISSUE #165: Create, update and delete a group
**DoR**
- [x] Acceptance criterias are defined
- [x] Stakeholders and contact persons are known
- [x] Description (scope) is understood by the team
- [x] Automation Tests affected, needed or possible

**DoD**
- [ ] Story is reviewed and accepted by PO
- [ ] Story is tested by DEV-Engineer
- [ ] Documentation extended if required

---

**Business value**
As a user, I want to group my habits, so that I have a better overview.

**Description**

**Open points**

**Preconditions**

**Acceptance criterias**
- Group entity is end to end implemented

**Not in scope**

**Implementation details**

**Test case description**
Not needed.

**Involved contacts**
PO: @Andy-Bigler  
TE: @Andy-Bigler

### PR DESCRIPTION
**Pull request by janfuhrer**
closes #165 #166

### CODE REVIEW

**Comment by janfuhrer** [comment]
open tasks in UI:

- remove group from habit in UI
- add filter for group in UI
- create/update/delete group in UI

**Comment by Andy-Bigler** [comment]
Backend changes look good to me 👍

**Comment by Andy-Bigler** [comment]
Are the open points all done now?

**Review by Andy-Bigler — APPROVED** [review]
lgtm

**Pull request merged**
